### ISSUE TITLE
Patch the main template file

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/dokuwiki-git-merge#2]
In order for the git merge tool to work we need to apply this patch to `lib/tpl/door43/main.php`
This patch adds a hook that extensions can use to change the tools on the right side of a page.

```
90,95c90,109
<                             tpl_action('edit',      1, 'li', 0, '<span>', '</span>');
<                             tpl_action('revert',    1, 'li', 0, '<span>', '</span>');
<                             tpl_action('revisions', 1, 'li', 0, '<span>', '</span>');
<                             tpl_action('backlink',  1, 'li', 0, '<span>', '</span>');
<                             tpl_action('subscribe', 1, 'li', 0, '<span>', '</span>');
<                             tpl_action('top',       1, 'li', 0, '<span>', '</span>');
---
>                             $data = array(
>                                 'view'  => 'main',
>                                 'items' => array(
>                                     'edit'      => tpl_action('edit',      true, 'li', true, '<span>', '</span>'),
>                                     'revert'    => tpl_action('revert',    true, 'li', true, '<span>', '</span>'),
>                                     'revisions' => tpl_action('revisions', true, 'li', true, '<span>', '</span>'),
>                                     'backlink'  => tpl_action('backlink',  true, 'li', true, '<span>', '</span>'),
>                                     'subscribe' => tpl_action('subscribe', true, 'li', true, '<span>', '</span>'),
>                                     'top'       => tpl_action('top',       true, 'li', true, '<span>', '</span>')
>                                 )
>                             );
> 
>                             // the page tools can be amended through a custom plugin hook
>                             $evt = new Doku_Event('TEMPLATE_PAGETOOLS_DISPLAY', $data);
>                             if($evt->advise_before()){
>                                 foreach($evt->data['items'] as $k => $html) echo $html;
>                             }
>                             $evt->advise_after();
>                             unset($data);
>                             unset($evt);
```

**Comment by neutrinog** [comment]
I have the actual file, but github won't let me upload it. Also, I'll test this on the test server first. So you can hold off on this.

**Comment by phillip-hopper** [comment]
@neutrinog , can you fork the repository, update the file in the fork, then create a pull request?

**Comment by neutrinog** [comment]
@phillip-hopper which repo is it?

**Comment by phillip-hopper** [comment]
@neutrinog I would just add it to this repo, in a folder named "private" or something like that.

**Comment by phillip-hopper** [comment]
@jag3773 Is the dokuwiki base code maintained in a door43 repo?

**Comment by jag3773** [comment]
No.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
@phillip-hopper you can find the patch here https://github.com/unfoldingWord-dev/dokuwiki-git-merge/tree/master/patch

**Comment by phillip-hopper** [comment]
Done

**Comment by phillip-hopper** [comment]
@neutrinog , I have the plugin installed on test.door43.org and the home page patched, but I haven't been able to get it working. Do you have any suggestions?

**Comment by neutrinog** [comment]
thanks @phillip-hopper . There are a few settings that need to be configured after the plugin is installed. I'll have the README updated with instructions and let you know.

**Comment by neutrinog** [comment]
@phillip-hopper the readme has been updated with some additional instructions.
Let me know if you run into any more problems.

**Comment by neutrinog** [comment]
@phillip-hopper I do need to make some changes in the app before the results are actually seen by the plugin. But I can ssh in and set up a simulation. Later we'll probably work in some backwards compatibility for old translation repos
