### ISSUE TITLE
Install latest version of plugin on the test server

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/dokuwiki-git-merge#5]
Make sure to set up the git repository path as explained in the README. Then visit http://test.door43.org/en/obs/01?do=door43gitmerge-crawl to trigger the initial indexing.

> Note: the url above initiates a manual crawl over the repo and sets up some json files. Eventually this will be handled automatically using githooks. So for now this is the poor man's git hook.

**Comment by neutrinog** [comment]
UPDATE: we do have a git hook now. See https://github.com/unfoldingWord-dev/dokuwiki-git-merge/issues/6

**Comment by kbuildsyourdotcom** [comment]
To make sure no possible merge updates are missing, the crawl should be triggered both before and after the git hooks are put into place.

**Comment by neutrinog** [comment]
@phillip-hopper I'll try to set this up some time Friday or Saturday if you are not able to work on this before. Let me know otherwise.
